/**
 * External dependencies
 *
 * @ignore
 */
import { invoke, nth } from 'lodash';

/**
 * Extracts block specific CSS class name generated by Gutenberg editor.
 * By default the block CSS class name is prefixed with `wp-block` keyword.
 *
 * @function
 * @since       1.0.0
 * @name        blockClassName
 * @param       {string}    input    CSS class names assigned to the block.
 * @return      {string}             CSS class name generated for the block.
 * @example
 *
 * blockClassName( 'wp-block-prefix-spacer custom-class-name test-class-name' );
 *
 * // => string 'wp-block-prefix-spacer'
 */
export default ( input ) => nth( invoke( input, 'match', /wp-block-[^{\s]*/ ) );
